import * as THREE from 'three';
import type { BucketState } from './bucketTypes';
import type { SampledPoint } from '../primitives/types';

export function createBucket(count: number, pointSize: number = 0.4, opacity: number = 0.8): BucketState {
  // Create a soft glowing circle texture
  const canvas = document.createElement('canvas');
  canvas.width = 64;
  canvas.height = 64;
  const context = canvas.getContext('2d')!;
  const gradient = context.createRadialGradient(32, 32, 0, 32, 32, 32);
  gradient.addColorStop(0, 'rgba(255,255,255,1)');
  gradient.addColorStop(0.15, 'rgba(255,255,255,0.9)');
  gradient.addColorStop(0.4, 'rgba(255,255,255,0.1)'); // Sharper falloff reduces muddy blending
  gradient.addColorStop(1, 'rgba(255,255,255,0)');
  context.fillStyle = gradient;
  context.fillRect(0, 0, 64, 64);
  const texture = new THREE.CanvasTexture(canvas);

  // Create a solid circular texture for light mode
  const canvasSolid = document.createElement('canvas');
  canvasSolid.width = 64;
  canvasSolid.height = 64;
  const contextSolid = canvasSolid.getContext('2d')!;
  contextSolid.beginPath();
  contextSolid.arc(32, 32, 28, 0, Math.PI * 2);
  contextSolid.fillStyle = 'rgba(255,255,255,1)';
  contextSolid.fill();
  const textureSolid = new THREE.CanvasTexture(canvasSolid);

  const positions = new Float32Array(count * 3);
  const colors = new Float32Array(count * 3);
  const targetLocalPositions = new Float32Array(count * 3);
  const targetColors = new Float32Array(count * 3);

  // Initialize perfectly hidden at infinity
  for (let i = 0; i < count; i++) {
    positions[i * 3 + 0] = 0;
    positions[i * 3 + 1] = 0;
    positions[i * 3 + 2] = 99999;

    targetLocalPositions[i * 3 + 0] = 0;
    targetLocalPositions[i * 3 + 1] = 0;
    targetLocalPositions[i * 3 + 2] = 99999;

    colors[i * 3 + 0] = 0;
    colors[i * 3 + 1] = 0;
    colors[i * 3 + 2] = 0;

    targetColors[i * 3 + 0] = 0;
    targetColors[i * 3 + 1] = 0;
    targetColors[i * 3 + 2] = 0;
  }

  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
  geometry.setAttribute('color', new THREE.BufferAttribute(colors, 3));

  const material = new THREE.PointsMaterial({
    size: pointSize,
    map: texture,
    vertexColors: true,
    transparent: true,
    opacity: opacity,
    sizeAttenuation: true,
    depthWrite: false, // helps with blending
    blending: THREE.AdditiveBlending
  });

  const points = new THREE.Points(geometry, material);

  return {
    count,
    positions,
    colors,
    targetLocalPositions,
    targetColors,
    geometry,
    points,
    anchor: new THREE.Vector3(),
    scale: new THREE.Vector3(1, 1, 1),
    rotation: new THREE.Euler(),
    baseRotation: new THREE.Euler(),
    transitionProgress: 0.05, // default ease rate
    textureBloom: texture,
    textureSolid
  };
}

export function setBucketTarget(bucket: BucketState, targetPoints: SampledPoint[], color1?: THREE.Color, color2?: THREE.Color, activePoints?: number, theme?: string) {
  const minCount = Math.min(bucket.count, targetPoints.length);
  const activeLimit = activePoints !== undefined ? activePoints : minCount;
  bucket.activeCount = activeLimit;

  for (let i = 0; i < minCount; i++) {
    const p = targetPoints[i];
    bucket.targetLocalPositions[i * 3 + 0] = p.position.x;
    bucket.targetLocalPositions[i * 3 + 1] = p.position.y;
    bucket.targetLocalPositions[i * 3 + 2] = p.position.z;

    let c = p.color || new THREE.Color(1, 1, 1);
    
    // Explicit padding points generated by normalizePointSet use perfect (0,0,0) geometry
    const isPaddingPoint = p.color && p.color.r === 0 && p.color.g === 0 && p.color.b === 0;
    const isOutOfBounds = i >= activeLimit || isPaddingPoint;

    if (isOutOfBounds) {
      // Additive Blending natively vanishes with (0,0,0). NormalBlending (light bucketHover) needs the exact background hue.
      const isAdditive = (bucket.points.material as THREE.PointsMaterial).blending === THREE.AdditiveBlending;
      c = (theme === 'light' && !isAdditive) ? new THREE.Color(0.941, 0.941, 0.941) : new THREE.Color(0, 0, 0);
      
      // Push completely unseen unused padding points massively deep into Z and out of frame
      // This enforces Z-occlusion naturally while maintaining transparency.
      bucket.targetLocalPositions[i * 3 + 0] = p.position.x; 
      bucket.targetLocalPositions[i * 3 + 1] = p.position.y; 
      bucket.targetLocalPositions[i * 3 + 2] = 99999; 
    } else if (color1 && color2) {
      // Golden ratio pseudo-random distribution so the random splatter doesn't flicker on scroll-transitions
      const ratio = ((i * 137.5) % 1000) / 1000;
      c = new THREE.Color().copy(color1).lerp(color2, ratio);
    } else if (color1) {
      c = color1;
    }

    bucket.targetColors[i * 3 + 0] = c.r;
    bucket.targetColors[i * 3 + 1] = c.g;
    bucket.targetColors[i * 3 + 2] = c.b;
  }
}
